Repository alliance-genome/agr_curation, pull requests merged in 2022-10, with the labels that each got.

#682 SCRUM-2131 Allow mutiple asserted genes
  src/main/cliapp/src/containers/diseaseAnnotationsPage/DiseaseAnnotationsTable.js
  src/main/java/org/alliancegenome/curation_api/constants/LinkMLSchemaConstants.java
  src/main/java/org/alliancegenome/curation_api/model/entities/AGMDiseaseAnnotation.java
  src/main/java/org/alliancegenome/curation_api/model/entities/AlleleDiseaseAnnotation.java
  src/main/java/org/alliancegenome/curation_api/model/ingest/dto/AGMDiseaseAnnotationDTO.java
  src/main/java/org/alliancegenome/curation_api/model/ingest/dto/AlleleDiseaseAnnotationDTO.java
  src/main/java/org/alliancegenome/curation_api/services/AGMDiseaseAnnotationService.java
  src/main/java/org/alliancegenome/curation_api/services/AlleleDiseaseAnnotationService.java
  src/main/java/org/alliancegenome/curation_api/services/helpers/validators/AGMDiseaseAnnotationValidator.java
  src/main/java/org/alliancegenome/curation_api/services/helpers/validators/AlleleDiseaseAnnotationValidator.java
  src/main/resources/db/migration/v0.11.0.2__agr_curation_api.sql
  src/test/java/org/alliancegenome/curation_api/bulkupload/DiseaseAnnotationBulkUploadITCase.java
  src/test/java/org/alliancegenome/curation_api/crud/controllers/DiseaseAnnotationITCase.java
  src/test/resources/bulk/04_disease_annotation/02_all_fields_allele_annotation.json
  src/test/resources/bulk/04_disease_annotation/03_all_fields_agm_annotation.json
  src/test/resources/bulk/04_disease_annotation/109_empty_asserted_genes_allele_annotation.json
  src/test/resources/bulk/04_disease_annotation/123_empty_asserted_genes_agm_annotation.json
  src/test/resources/bulk/04_disease_annotation/76_invalid_asserted_gene_allele_annotation.json
  src/test/resources/bulk/04_disease_annotation/82_invalid_asserted_gene_agm_annotation.json
Labels: reindex required

#709 SCRUM-2139 Return exact matches only from dropdown filters
  src/main/cliapp/src/containers/allelesPage/AllelesTable.js
  src/main/cliapp/src/containers/diseaseAnnotationsPage/DiseaseAnnotationsTable.js
  src/main/resources/db/migration/v0.11.0.7__agr_curation_api.sql
  src/test/java/org/alliancegenome/curation_api/bulkupload/AlleleBulkUploadITCase.java
  src/test/java/org/alliancegenome/curation_api/crud/controllers/AlleleITCase.java
  src/test/resources/bulk/02_allele/01_all_fields_allele.json
  src/test/resources/bulk/02_allele/02_no_curie_allele.json
  src/test/resources/bulk/02_allele/03_no_name_allele.json
  src/test/resources/bulk/02_allele/04_no_symbol_allele.json
  src/test/resources/bulk/02_allele/05_no_taxon_allele.json
  src/test/resources/bulk/02_allele/06_no_internal_allele.json
  src/test/resources/bulk/02_allele/07_no_created_by_allele.json
  src/test/resources/bulk/02_allele/08_no_updated_by_allele.json
  src/test/resources/bulk/02_allele/09_no_date_created_allele.json
  src/test/resources/bulk/02_allele/10_no_date_updated_allele.json
  src/test/resources/bulk/02_allele/11_invalid_taxon_allele.json
  src/test/resources/bulk/02_allele/12_invalid_date_created_allele.json
  src/test/resources/bulk/02_allele/13_invalid_date_updated_allele.json
  src/test/resources/bulk/02_allele/14_no_obsolete_allele.json
  src/test/resources/bulk/02_allele/15_empty_symbol_allele.json
  src/test/resources/bulk/02_allele/16_empty_updated_by_allele.json
  src/test/resources/bulk/02_allele/17_empty_name_allele.json
  src/test/resources/bulk/02_allele/18_empty_created_by_allele.json
  src/test/resources/bulk/02_allele/19_empty_date_updated_allele.json
  src/test/resources/bulk/02_allele/20_empty_date_created_allele.json
  src/test/resources/bulk/02_allele/21_empty_curie_allele.json
  src/test/resources/bulk/02_allele/22_empty_taxon_allele.json
  src/test/resources/bulk/02_allele/23_no_inheritance_mode_allele.json
  src/test/resources/bulk/02_allele/25_no_sequencing_status_allele.json
  src/test/resources/bulk/02_allele/26_no_is_extinct_allele.json
  src/test/resources/bulk/02_allele/27_no_references_allele.json
  src/test/resources/bulk/02_allele/28_invalid_inheritance_mode_allele.json
  src/test/resources/bulk/02_allele/30_invalid_sequencing_status_allele.json
  src/test/resources/bulk/02_allele/31_invalid_reference_allele.json
Labels: reindex required

#712 Added release notes for 0.11.0
  RELEASE-NOTES.md
Labels: no-deploy

#720 SCRUM-2161 Make allele attributes editable
  src/main/cliapp/src/components/GenericDataTable/GenericDataTable.js
  src/main/cliapp/src/components/TrueFalseDropDownSelector.js
  src/main/cliapp/src/containers/allelesPage/AllelesTable.js
  src/main/cliapp/src/containers/experimentalConditionsPage/ExperimentalConditionsTable.js
  src/main/cliapp/src/service/AlleleService.js
  src/main/java/org/alliancegenome/curation_api/interfaces/crud/AlleleCrudInterface.java
  src/main/java/org/alliancegenome/curation_api/model/entities/Allele.java
  src/main/java/org/alliancegenome/curation_api/model/entities/BiologicalEntity.java
  src/main/java/org/alliancegenome/curation_api/services/validation/AlleleValidator.java
  src/main/java/org/alliancegenome/curation_api/services/validation/GenomicEntityValidator.java
  src/main/java/org/alliancegenome/curation_api/view/View.java
Labels: reindex required

#727 Add LinkML version submission documentation
  README.md
Labels: no-deploy

#744 SCRUM-2223 Fix discrepancy in publication curies used for DA and CR uniqueId fields
  src/main/java/org/alliancegenome/curation_api/services/helpers/diseaseAnnotations/DiseaseAnnotationCurie.java
  src/main/java/org/alliancegenome/curation_api/services/helpers/diseaseAnnotations/FlyDiseaseAnnotationCurie.java
  src/main/java/org/alliancegenome/curation_api/services/helpers/diseaseAnnotations/MGIDiseaseAnnotationCurie.java
  src/main/java/org/alliancegenome/curation_api/services/helpers/diseaseAnnotations/RGDDiseaseAnnotationCurie.java
  src/main/java/org/alliancegenome/curation_api/services/helpers/diseaseAnnotations/SGDDiseaseAnnotationCurie.java
  src/main/java/org/alliancegenome/curation_api/services/helpers/diseaseAnnotations/WormDiseaseAnnotationCurie.java
  src/main/java/org/alliancegenome/curation_api/services/helpers/diseaseAnnotations/ZFINDiseaseAnnotationCurie.java
  src/main/java/org/alliancegenome/curation_api/services/validation/dto/AGMDiseaseAnnotationDTOValidator.java
  src/main/java/org/alliancegenome/curation_api/services/validation/dto/AlleleDiseaseAnnotationDTOValidator.java
  src/main/java/org/alliancegenome/curation_api/services/validation/dto/ConditionRelationDTOValidator.java
  src/main/java/org/alliancegenome/curation_api/services/validation/dto/DiseaseAnnotationDTOValidator.java
  src/main/java/org/alliancegenome/curation_api/services/validation/dto/GeneDiseaseAnnotationDTOValidator.java
  src/main/resources/db/migration/v0.12.0.4__agr_curation_api.sql
  src/test/java/org/alliancegenome/curation_api/bulkupload/DiseaseAnnotationBulkUploadITCase.java
Labels: data load required
